//go:build tongsuocli

// Package ecdh 的 tongsuocli 对拍测试（真实调用铜锁 openssl CLI）。
// Build tag: tongsuocli (off by default)；运行方式见 docs/testing-guide.md §2。
package ecdh

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/blue-cloud-net/tongsuo-go/internal/testutil"
)

// cliCurve 描述一条参与 CLI 对拍的曲线。
//
// cliCurve describes one curve participating in the CLI interop tests.
type cliCurve struct {
	name    string   // 展示名，与 (*Curve).Name() 一致
	curve   *Curve   // 本库曲线构造函数的结果
	genArgs []string // openssl genpkey 的算法相关参数
	marker  string   // `pkey -text` 输出中应含的曲线标记
}

// cliCurves 返回对拍曲线集合；OKP 曲线（X25519 / X448）与 secp256k1 依赖
// 运行时 provider，不可用时由各用例自行跳过。
//
// cliCurves returns the curve set used by the CLI interop tests. The OKP
// curves (X25519 / X448) and secp256k1 depend on the runtime provider and
// are skipped by individual subtests when unavailable.
func cliCurves() []cliCurve {
	return []cliCurve{
		{
			name:    "P-256",
			curve:   P256(),
			genArgs: []string{"-algorithm", "EC", "-pkeyopt", "ec_paramgen_curve:prime256v1"},
			marker:  "prime256v1",
		},
		{
			name:    "P-384",
			curve:   P384(),
			genArgs: []string{"-algorithm", "EC", "-pkeyopt", "ec_paramgen_curve:secp384r1"},
			marker:  "secp384r1",
		},
		{
			name:    "P-521",
			curve:   P521(),
			genArgs: []string{"-algorithm", "EC", "-pkeyopt", "ec_paramgen_curve:secp521r1"},
			marker:  "secp521r1",
		},
		{
			name:    "secp256k1",
			curve:   Secp256k1(),
			genArgs: []string{"-algorithm", "EC", "-pkeyopt", "ec_paramgen_curve:secp256k1"},
			marker:  "secp256k1",
		},
		{
			name:    "X25519",
			curve:   X25519(),
			genArgs: []string{"-algorithm", "X25519"},
			marker:  "X25519",
		},
		{
			name:    "X448",
			curve:   X448(),
			genArgs: []string{"-algorithm", "X448"},
			marker:  "X448",
		},
	}
}

// TestCLIParsesLibraryPEM 验证本库导出的私钥 / 公钥 PEM 能被 CLI 解析，且曲线识别正确。
//
// TestCLIParsesLibraryPEM verifies the CLI can parse the private/public PEM
// produced by this library and reports the expected curve.
func TestCLIParsesLibraryPEM(t *testing.T) {
	bin := testutil.SkipIfNoOpenSSL(t)
	for _, tc := range cliCurves() {
		t.Run(tc.name, func(t *testing.T) {
			priv, err := tc.curve.GenerateKey()
			if err != nil {
				t.Skipf("%s unavailable in this Tongsuo build: %v", tc.name, err)
			}
			privPEM, err := priv.MarshalPEM()
			if err != nil {
				t.Fatalf("MarshalPEM: %v", err)
			}
			pubPEM, err := priv.Public().MarshalPEM()
			if err != nil {
				t.Fatalf("Public MarshalPEM: %v", err)
			}
			dir := t.TempDir()
			privPath := writeTemp(t, dir, "priv.pem", privPEM)
			pubPath := writeTemp(t, dir, "pub.pem", pubPEM)

			out, err := runOpenSSL(t, bin, "pkey", "-in", privPath, "-noout", "-text")
			if err != nil {
				t.Fatalf("cli pkey private: %v\n%s", err, out)
			}
			if !bytes.Contains(out, []byte(tc.marker)) {
				t.Fatalf("private key output missing %q marker:\n%s", tc.marker, out)
			}
			out, err = runOpenSSL(t, bin, "pkey", "-in", pubPath, "-pubin", "-noout", "-text")
			if err != nil {
				t.Fatalf("cli pkey public: %v\n%s", err, out)
			}
			if !bytes.Contains(out, []byte(tc.marker)) {
				t.Fatalf("public key output missing %q marker:\n%s", tc.marker, out)
			}
		})
	}
}

// TestCLIGeneratedKeyLoads 验证 CLI 生成的密钥与本库互通（私钥 + `-pubout` 公钥均可加载）。
//
// TestCLIGeneratedKeyLoads verifies keys generated by the CLI are loadable
// with this library, both the private key and the `-pubout` public key.
func TestCLIGeneratedKeyLoads(t *testing.T) {
	bin := testutil.SkipIfNoOpenSSL(t)
	for _, tc := range cliCurves() {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			privPath := filepath.Join(dir, "cli.pem")
			args := append([]string{"genpkey"}, tc.genArgs...)
			args = append(args, "-out", privPath)
			if out, err := runOpenSSL(t, bin, args...); err != nil {
				t.Skipf("cli genpkey %s unsupported: %v\n%s", tc.name, err, out)
			}
			privPEM, err := os.ReadFile(privPath)
			if err != nil {
				t.Fatalf("read cli pem: %v", err)
			}
			priv, err := LoadPrivateKeyPEM(tc.curve, privPEM)
			if err != nil {
				t.Fatalf("LoadPrivateKeyPEM: %v", err)
			}
			if got := priv.Key().Algorithm(); got == "" {
				t.Fatal("loaded key reports an empty algorithm")
			}

			pubPath := filepath.Join(dir, "cli_pub.pem")
			if out, err := runOpenSSL(t, bin, "pkey", "-in", privPath, "-pubout", "-out", pubPath); err != nil {
				t.Fatalf("cli pkey -pubout: %v\n%s", err, out)
			}
			pubPEM, err := os.ReadFile(pubPath)
			if err != nil {
				t.Fatalf("read cli pub pem: %v", err)
			}
			if _, err := LoadPublicKeyPEM(tc.curve, pubPEM); err != nil {
				t.Fatalf("LoadPublicKeyPEM: %v", err)
			}
		})
	}
}

// TestCLIDeriveMatchesLibrary 用 `openssl pkeyutl -derive` 对本库共享密钥做逐字节对拍。
//
// 铜锁 CLI 对 ECX 曲线（X25519 / X448）可能不支持 `pkeyutl -derive`，此时子用例跳过
// 并说明原因；该路径由 crypto/x25519 与 crypto/x448 的「CLI 造钥 + 本库派生」用例覆盖。
//
// TestCLIDeriveMatchesLibrary byte-compares the library shared secret against
// `openssl pkeyutl -derive`. When the Tongsuo CLI does not support -derive for
// a curve (notably the ECX curves) the subtest skips with an explanation;
// crypto/x25519 and crypto/x448 cover that path through CLI keygen plus
// library-side derivation.
func TestCLIDeriveMatchesLibrary(t *testing.T) {
	bin := testutil.SkipIfNoOpenSSL(t)
	for _, tc := range cliCurves() {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			alicePath := filepath.Join(dir, "alice.pem")
			bobPath := filepath.Join(dir, "bob.pem")
			bobPubPath := filepath.Join(dir, "bob_pub.pem")

			gen := func(path string) {
				t.Helper()
				args := append([]string{"genpkey"}, tc.genArgs...)
				args = append(args, "-out", path)
				if out, err := runOpenSSL(t, bin, args...); err != nil {
					t.Skipf("cli genpkey %s unsupported: %v\n%s", tc.name, err, out)
				}
			}
			gen(alicePath)
			gen(bobPath)
			if out, err := runOpenSSL(t, bin, "pkey", "-in", bobPath, "-pubout", "-out", bobPubPath); err != nil {
				t.Fatalf("cli pkey -pubout: %v\n%s", err, out)
			}

			sharedPath := filepath.Join(dir, "shared.bin")
			if out, err := runOpenSSL(t, bin, "pkeyutl", "-derive",
				"-inkey", alicePath, "-peerkey", bobPubPath, "-out", sharedPath); err != nil {
				t.Skipf("cli pkeyutl -derive unsupported for %s: %v\n%s", tc.name, err, out)
			}
			cliShared, err := os.ReadFile(sharedPath)
			if err != nil {
				t.Fatalf("read cli shared secret: %v", err)
			}

			alicePEM, err := os.ReadFile(alicePath)
			if err != nil {
				t.Fatalf("read alice pem: %v", err)
			}
			bobPubPEM, err := os.ReadFile(bobPubPath)
			if err != nil {
				t.Fatalf("read bob pub pem: %v", err)
			}
			alicePriv, err := LoadPrivateKeyPEM(tc.curve, alicePEM)
			if err != nil {
				t.Fatalf("LoadPrivateKeyPEM: %v", err)
			}
			bobPub, err := LoadPublicKeyPEM(tc.curve, bobPubPEM)
			if err != nil {
				t.Fatalf("LoadPublicKeyPEM: %v", err)
			}
			got, err := alicePriv.ECDH(bobPub)
			if err != nil {
				t.Fatalf("ECDH: %v", err)
			}
			if !bytes.Equal(got, cliShared) {
				t.Fatalf("shared secret mismatch (%s):\n  lib = %x\n  cli = %x", tc.name, got, cliShared)
			}
		})
	}
}

// writeTemp 把数据写入 dir/name（0600）并返回完整路径。
//
// writeTemp writes data to dir/name with mode 0600 and returns the path.
func writeTemp(t *testing.T, dir, name string, data []byte) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return path
}

// runOpenSSL 执行铜锁 CLI 并返回合并后的输出。
//
// runOpenSSL runs the Tongsuo CLI and returns its combined output.
func runOpenSSL(t *testing.T, bin string, args ...string) ([]byte, error) {
	t.Helper()
	return exec.Command(bin, args...).CombinedOutput()
}